server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启当前项目服务注册也发现功能
          lower-case-service-id: true # 把服务名转换为小写，Eureka中默认都是大写
      routes:
        - id: banner #自定义唯一标识，只要不重复即可
          uri: lb://BANNER-SHOW # lb:loadBalance EUREKA-CLIENT 代理项目的名
          predicates: Path=/api/banner # 路径规则
          filters: StripPrefix=1 # 转发后忽略第一层
        - id: hotProduct
          uri: lb://ITEM-HOTPRODUCT
          predicates: Path=/api/hotProduct #接口文档中地址
          filters: StripPrefix=1
        - id: recommendation
          uri: lb://ITEM-RECOMMENDATION
          predicates: Path=/api/recommendation #接口文档中地址
          filters: StripPrefix=1
        - id: search
          uri: lb://HOUSE-SEARCH
          predicates: Path=/api/search #接口文档中地址
          filters: StripPrefix=1
        - id: details
          uri: lb://HOUSE-DETAILS
          predicates: Path=/api/details #接口文档中地址
          filters: StripPrefix=1
        - id: comment
          uri: lb://COMMENT-SHOW
          predicates: Path=/api/comment #接口文档中地址
          filters: StripPrefix=1
        - id: buytime
          uri: lb://HOUSE-BUYTIME
          predicates: Path=/api/buytime #接口文档中地址
          filters: StripPrefix=1
        - id: sendyzm
          uri: lb://VALIDATECODE-SENDYZM
          predicates: Path=/api/sendyzm #接口文档中地址
          filters: StripPrefix=1
        - id: login
          uri: lb://USER-LOGIN
          predicates: Path=/api/login #接口文档中地址
          filters: StripPrefix=1
        - id: buyaction
          uri: lb://HOUSE-BUYACTION
          predicates: Path=/api/buyaction #接口文档中地址
          filters: StripPrefix=1
        - id: order
          uri: lb://ORDER-SHOW
          predicates: Path=/api/order #接口文档中地址
          filters: StripPrefix=1
        - id: feelback
          uri: lb://ORDER-FEELBACK
          predicates: Path=/api/feelback #接口文档中地址
          filters: StripPrefix=1