spring:
  application:
    name: house-byid
  data:
    mongodb:
      authentication-database: admin
      username: dywei
      password: dywei
      database: livegoods
      port: 27017
      host: 192.168.8.133
server:
  port: 8090