spring:
  application:
    name: house-details
  data:
    mongodb:
      authentication-database: admin
      username: dywei
      password: dywei
      database: livegoods
      port: 27017
      host: 192.168.8.133
  redis:
    host: 192.168.8.132
  rabbitmq:
    host: 192.168.8.136
    username: dywei
    password: dywei
server:
  port: 8100