spring:
  application:
    name: user-selectbyuser
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: dywei
  data:
    mongodb:
      authentication-database: admin
      username: dywei
      password: dywei
      database: livegoods
      port: 27017
      host: 192.168.8.133
server:
  port: 8097
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070