spring:
  application:
    name: user-login
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: dywei
server:
  port: 8098
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
feign:
  hystrix:
    enabled: true